
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author maxat
 */
public class EstateAgentReport extends javax.swing.JFrame {

    /**
     * Creates new form EstateAgentReport
     */
    public EstateAgentReport() {
        initComponents();
    }

    // Basic validation check to see if the fields are empty.
    // NOTE: This is will not validate the data entered. 
    public boolean validLocation() {
        // Will always return true, as user is forced to chose a location
        return true;
    }

    public boolean validName() {
        return !AgentNameTextField.getText().equals("");
    }

    public boolean validPrice() {
        return !PropertyPriceTextField.getText().equals("");
    }

    public boolean validPercentage() {
        return !CommissionPercentageTextField.getText().equals("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgentLocationLabel = new javax.swing.JLabel();
        EstateAgentNameLabel = new javax.swing.JLabel();
        PropertyPriceLabel = new javax.swing.JLabel();
        CommissionPercentageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EstateAgentReportTextArea = new javax.swing.JTextArea();
        AgentNameTextField = new javax.swing.JTextField();
        PropertyPriceTextField = new javax.swing.JTextField();
        LocationComboBox = new javax.swing.JComboBox<>();
        CommissionPercentageTextField = new javax.swing.JTextField();
        ReportLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        ExitMenuItem_File = new javax.swing.JMenuItem();
        Tools = new javax.swing.JMenu();
        ProcessReportMenuItem_Tools = new javax.swing.JMenuItem();
        ClearMenuItem_Tools = new javax.swing.JMenuItem();
        SaveReportMenuItem_Tools = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AgentLocationLabel.setText("AGENT LOCATION");

        EstateAgentNameLabel.setText("ESTATE AGENT NAME");

        PropertyPriceLabel.setText("PROPERTY PRICE");

        CommissionPercentageLabel.setText("COMMISSION PERCENTAGE");

        EstateAgentReportTextArea.setEditable(false);
        EstateAgentReportTextArea.setColumns(20);
        EstateAgentReportTextArea.setRows(5);
        jScrollPane1.setViewportView(EstateAgentReportTextArea);

        AgentNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentNameTextFieldActionPerformed(evt);
            }
        });

        PropertyPriceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropertyPriceTextFieldActionPerformed(evt);
            }
        });

        LocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cape Town", "Durban", "Pretoria" }));

        CommissionPercentageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommissionPercentageTextFieldActionPerformed(evt);
            }
        });

        ReportLabel.setText("ESTATE AGENT REPORT");

        File.setText("File");
        File.setToolTipText("Exit");

        ExitMenuItem_File.setText("Exit");
        ExitMenuItem_File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItem_FileActionPerformed(evt);
            }
        });
        File.add(ExitMenuItem_File);

        jMenuBar1.add(File);

        Tools.setText("Tools");

        ProcessReportMenuItem_Tools.setText("Process Report");
        ProcessReportMenuItem_Tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessReportMenuItem_ToolsActionPerformed(evt);
            }
        });
        Tools.add(ProcessReportMenuItem_Tools);

        ClearMenuItem_Tools.setText("Clear");
        ClearMenuItem_Tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearMenuItem_ToolsActionPerformed(evt);
            }
        });
        Tools.add(ClearMenuItem_Tools);

        SaveReportMenuItem_Tools.setText("Save Report");
        SaveReportMenuItem_Tools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveReportMenuItem_ToolsActionPerformed(evt);
            }
        });
        Tools.add(SaveReportMenuItem_Tools);

        jMenuBar1.add(Tools);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EstateAgentNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AgentLocationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PropertyPriceLabel)
                            .addComponent(CommissionPercentageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PropertyPriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(CommissionPercentageTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReportLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AgentLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstateAgentNameLabel)
                    .addComponent(AgentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PropertyPriceLabel)
                    .addComponent(PropertyPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CommissionPercentageLabel)
                    .addComponent(CommissionPercentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ReportLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitMenuItem_FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItem_FileActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitMenuItem_FileActionPerformed

    private void ProcessReportMenuItem_ToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessReportMenuItem_ToolsActionPerformed

        String agentName = null;
        double price = 0, commission = 0, calcCommission = 0;
        String location = LocationComboBox.getItemAt(LocationComboBox.getSelectedIndex());

        // Check to see if fields are populated
        if (validName() && validPrice() && validPercentage()) {
            agentName = AgentNameTextField.getText();
            price = Double.parseDouble(PropertyPriceTextField.getText());
            commission = Double.parseDouble(CommissionPercentageTextField.getText());
            calcCommission = (commission / 100) * price;

            String report = "ESATE LOCATION: \t" + location;
            report += "\nAGENT NAME: \t\t" + agentName;
            report += "\nPROPERTY PRICE: \tR " + price;
            report += "\nCOMMISSION PERCENTAGE: \tR " + commission + "%";
            report += "\nCALCULATED COMMISSION: \tR " + calcCommission;

            EstateAgentReportTextArea.setText(report);
        } else {
            EstateAgentReportTextArea.setText("ERROR: Enter blank fields!!!");
        }
    }//GEN-LAST:event_ProcessReportMenuItem_ToolsActionPerformed

    private void AgentNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentNameTextFieldActionPerformed

    }//GEN-LAST:event_AgentNameTextFieldActionPerformed

    private void PropertyPriceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropertyPriceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PropertyPriceTextFieldActionPerformed

    private void ClearMenuItem_ToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearMenuItem_ToolsActionPerformed

        // Sets all the text boxes to blank
        // No need to reset Location Combo Box since it's always forced to 1 of 3 locations
        AgentNameTextField.setText("");
        PropertyPriceTextField.setText("");
        CommissionPercentageTextField.setText("");
        EstateAgentReportTextArea.setText("");
    }//GEN-LAST:event_ClearMenuItem_ToolsActionPerformed

    private void CommissionPercentageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommissionPercentageTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommissionPercentageTextFieldActionPerformed

    private void SaveReportMenuItem_ToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveReportMenuItem_ToolsActionPerformed

        if (!validName() && !validPrice() && !validPercentage()) {
            EstateAgentReportTextArea.setText("ERROR: Enter blank fields!!!");
        } else {
            // Create a file named report.txt
            try {
                File obj = new File("report.txt");
                if (obj.createNewFile()) {
                    System.out.println("File created, " + obj.getName());
                } else {
                    System.out.println("There was an error.");
                }
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }

            // Write to the file
            try {
                double calcCommission = (Double.parseDouble(CommissionPercentageTextField.getText()) / 100) * (Double.parseDouble(PropertyPriceTextField.getText()));
                String report = "ESTATE AGENT REPORT\n********************************";
                report += "\nESATE LOCATION: \t" + LocationComboBox.getItemAt(LocationComboBox.getSelectedIndex());
                report += "\nAGENT NAME: \t\t" + AgentNameTextField.getText();
                report += "\nPROPERTY PRICE: \tR " + PropertyPriceTextField.getText();
                report += "\nCOMMISSION PERCENTAGE: \tR " + CommissionPercentageTextField.getText() + "%";
                report += "\nCALCULATED COMMISSION: \tR " + calcCommission;
                report += "\n*******************************";

                FileWriter writer = new FileWriter("report.txt");
                writer.write(report);
                writer.close();
                System.out.println("Data saved to file.");
            } catch (IOException e) {
                System.out.println("An error occurred.");
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_SaveReportMenuItem_ToolsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstateAgentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstateAgentReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgentLocationLabel;
    public javax.swing.JTextField AgentNameTextField;
    private javax.swing.JMenuItem ClearMenuItem_Tools;
    private javax.swing.JLabel CommissionPercentageLabel;
    public javax.swing.JTextField CommissionPercentageTextField;
    private javax.swing.JLabel EstateAgentNameLabel;
    private javax.swing.JTextArea EstateAgentReportTextArea;
    private javax.swing.JMenuItem ExitMenuItem_File;
    private javax.swing.JMenu File;
    public javax.swing.JComboBox<String> LocationComboBox;
    private javax.swing.JMenuItem ProcessReportMenuItem_Tools;
    private javax.swing.JLabel PropertyPriceLabel;
    public javax.swing.JTextField PropertyPriceTextField;
    private javax.swing.JLabel ReportLabel;
    private javax.swing.JMenuItem SaveReportMenuItem_Tools;
    private javax.swing.JMenu Tools;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
